plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.11'
	id 'io.spring.dependency-management' version '1.0.15.RELEASE'
	id 'jacoco'
}
java {
	sourceCompatibility = '11'
}
jacoco {
	toolVersion = "0.8.7"
}
jacocoTestReport {
	reports {
		xml.enabled true
		csv.enabled true
		html.enabled true

		xml.destination file("${buildDir}/jacoco/index.xml")
		csv.destination file("${buildDir}/jacoco/index.csv")
		html.destination file("${buildDir}/jacoco/index.html")
	}
//	afterEvaluate {
//		classDirectories.setFrom(
//				files(classDirectories.files.collect {
//					fileTree(dir: it, excludes: [
//							'**/*Application*',
//							'**/*Exception*',
//							'**/dto/**',
//							// ...
//					])
//				})
//		)
//	}
	finalizedBy 'jacocoTestCoverageVerification'
}
jacocoTestCoverageVerification {
	def QDomains = []
	// qPattern = "*.QA","*.QB","*.QC", ... "*.QZ"
	for (qPattern in '*.QA'..'*.QZ') {
		QDomains.add(qPattern + '*')
	}
//	violationRules {
//		rule {
//			// rule 활성화
//			enabled = true
//			// 클래스 단위로 룰 체크
//			element = 'CLASS'
//
//			excludes = [
//					"**.*Application*",
//					"**.*Config*",
//					"**.*Dto*",
//					"**.*Request*",
//					"**.*Response*",
//					"**.*Interceptor*",
//					"**.*Exception*"
//			] + QDomains
//		}
//	}
}
test {
	useJUnitPlatform()
	finalizedBy 'jacocoTestReport'
}


group = 'com.ime'
version = '0.0.1-SNAPSHOT'


configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	//spring
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation ('org.springframework.boot:spring-boot-starter-test')



	//lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	//jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	//jdbc
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'

	//mysql
	runtimeOnly 'com.mysql:mysql-connector-j'

	//valid
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	//security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'

	// jwt
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// H2
	runtimeOnly 'com.h2database:h2'

	//redisson
	implementation 'org.redisson:redisson-spring-boot-starter:3.22.1'

	//redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	//embed redis
	implementation("it.ozimov:embedded-redis:0.7.2")

	// Swagger
	implementation 'io.springfox:springfox-boot-starter:3.0.0'

	//WebClient
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	// testcontainers
	testImplementation "org.junit.jupiter:junit-jupiter:5.8.1"
	testImplementation "org.testcontainers:junit-jupiter:1.16.3"

	// queryDSL 설정
	implementation "com.querydsl:querydsl-jpa"
	implementation "com.querydsl:querydsl-core"
	implementation "com.querydsl:querydsl-collections"
	annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jpa" // querydsl JPAAnnotationProcessor 사용 지정
	annotationProcessor "jakarta.annotation:jakarta.annotation-api" // java.lang.NoClassDefFoundError (javax.annotation.Generated) 대응 코드
	annotationProcessor "jakarta.persistence:jakarta.persistence-api" // java.lang.NoClassDefFoundError (javax.annotation.Entity) 대응 코드

	//prometeus
	implementation 'io.micrometer:micrometer-registry-prometheus'

	//spring-actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

}

// Querydsl 설정부
def generated = 'src/main/generated'

// querydsl QClass 파일 생성 위치를 지정
tasks.withType(JavaCompile) {
	options.getGeneratedSourceOutputDirectory().set(file(generated))
}

tasks.withType(Test) {
	jacoco.includeNoLocationClasses = true
}

// java source set 에 querydsl QClass 위치 추가
sourceSets {
	main.java.srcDirs += [ generated ]
}

// gradle clean 시에 QClass 디렉토리 삭제
clean {
	delete file(generated)
}
jar {
	enabled = false
}